etl-create-agreement:
  image: innotech/etl-create-agreement:{{VERSION}}
  labels:
    io.rancher.container.pull_image: always
  external_links:
    - ${INPUT_KAFKA}:input_kafka
    - ${OUTPUT_KAFKA}:output_kafka
  environment:
    # Input
    - INPUT_KAFKA=input_kafka
    - TOPIC=${TOPIC}
    - OFFSET=${OFFSET}
    # Output
    - OUTPUT_KAFKA=output_kafka
    - TOPIC_OUTPUT=${TOPIC_OUTPUT}
    # Common
    - PRODUCTS=${PRODUCTS}
