.catalog:
  name: "etl-create-agreement"
  version: "{{VERSION}}"
  description: |
    ETL process that reads events from Kafka, produce a vector for each read event, write the vector in a another Kafka topic.
  minimum_rancher_version: "v0.46.0"
  questions:
    # Input
    - variable: "INPUT_KAFKA"
      description: "Name of input kafka broker service"
      label: "Input Kafka broker:"
      required: true
      default: "broker"
      type: "service"
    - variable: "TOPIC"
      description: "Kafka topic to consume"
      label: "Topic:"
      required: true
      default: "behavior-tests"
      type: "string"
    - variable: "OFFSET"
      description: "Offset to start consuming"
      label: "Offset:"
      required: true
      type: enum
      default: "newest"
      options:
        - newest
        - oldest
    # Output
    - variable: "OUTPUT_KAFKA"
      description: "Name of output kafka broker service"
      label: "Output Kafka broker:"
      required: true
      default: "broker"
      type: "service"
    - variable: "TOPIC_OUTPUT"
      description: "Kafka topic to produce"
      label: "Topic:"
      required: true
      default: "etl-create-agreement"
      type: "string"
    # Common
    - variable: "PRODUCTS"
      description: "Number of existing products"
      label: "Products:"
      required: true
      default: "5"
      type: "int"

etl-create-agreement:
  scale: "1"
